### ISSUE TITLE
meta()->noIndex() doesn't rewrite default value

### ISSUE THREAD

**Issue by t7team** [f9webltd/laravel-meta#19]
Hello I have  default value
```
'defaults' => [
        'charset' => 'utf-8',
        'robots' => 'index, follow',
...
```
When I use meta()->noIndex()
It doesn't rewrite default value. When I remove default value, it works.
What could it be?

**Comment by ultrono** [comment]
Apologies for missing this one!

I believe you've found an edge case as default values are not removed. So you have `index, follow` for the default robots tag. You've then later called `meta()->noIndex()` and expected the 

`noIndex()` is a macro, see https://github.com/f9webltd/laravel-meta/blob/master/src/MetaServiceProvider.php#L38-L43

The noIndex macro could simply call the `forget` method (see https://github.com/f9webltd/laravel-meta/blob/master/src/Meta.php#L72-L79), so the macro would become:

```
 Meta::macro(
            'noIndex',
            function () {
                Meta:forget('robots');
                return Meta::set('robots', 'noindex nofollow');
            }
        );
```

I'd definitely be open to a simple PR with tests on this, as you've uncovered a valid bug (I've only ever set meta robots within the defaults for internal system where the entire site would be not be indexed).

Thanks
